permalink: /:name/
base: http://mindshine.github.io/patent/

markdown: redcarpet
redcarpet:
  extensions: ['smart', 'superscript']

gems:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      lang: ua
      layout: default
  -
    scope:
      path: _posts/ua/pages
    values:
      type: pages
      desc: "Сайт реєстрації авторських прав на інтелектуальну власність"
  -
    scope:
      path: _posts/ru
    values:
      lang: ru
  -
    scope:
      path: _posts/ru/pages
    values:
      type: pages
      desc: "Сайт регистрации авторских прав на интеллектуальную собственность"
  -
    scope:
      path: _posts/en
    values:
      lang: en
  -
    scope:
      path: _posts/en/pages
    values:
      type: pages
      desc: "Site to registrate intillectual property"
